-- Module loading tests for lifecycle submodules
-- Validates that require() wiring works correctly after _set_*_module removal
-- Special attention to session ↔ accessors circular dependency

describe("Lifecycle submodules", function()
  describe("module loading", function()
    it("loads session module", function()
      local ok, mod = pcall(require, "codediff.ui.lifecycle.session")
      assert.is_true(ok, "Failed to require codediff.ui.lifecycle.session")
      assert.is_not_nil(mod)
    end)

    it("loads accessors module", function()
      local ok, mod = pcall(require, "codediff.ui.lifecycle.accessors")
      assert.is_true(ok, "Failed to require codediff.ui.lifecycle.accessors")
      assert.is_not_nil(mod)
    end)

    it("loads conflict_state module", function()
      local ok, mod = pcall(require, "codediff.ui.lifecycle.conflict_state")
      assert.is_true(ok, "Failed to require codediff.ui.lifecycle.conflict_state")
      assert.is_not_nil(mod)
    end)

    it("loads tab_keymaps module", function()
      local ok, mod = pcall(require, "codediff.ui.lifecycle.tab_keymaps")
      assert.is_true(ok, "Failed to require codediff.ui.lifecycle.tab_keymaps")
      assert.is_not_nil(mod)
    end)

    it("loads auto_sync module", function()
      local ok, mod = pcall(require, "codediff.ui.lifecycle.auto_sync")
      assert.is_true(ok, "Failed to require codediff.ui.lifecycle.auto_sync")
      assert.is_not_nil(mod)
    end)

    it("loads state module", function()
      local ok, mod = pcall(require, "codediff.ui.lifecycle.state")
      assert.is_true(ok, "Failed to require codediff.ui.lifecycle.state")
      assert.is_not_nil(mod)
    end)

    it("loads cleanup module", function()
      local ok, mod = pcall(require, "codediff.ui.lifecycle.cleanup")
      assert.is_true(ok, "Failed to require codediff.ui.lifecycle.cleanup")
      assert.is_not_nil(mod)
    end)

    it("loads init facade without circular dependency", function()
      local ok, mod = pcall(require, "codediff.ui.lifecycle")
      assert.is_true(ok, "Failed to require codediff.ui.lifecycle - possible circular dependency")
      assert.is_not_nil(mod)
    end)
  end)

  describe("public API", function()
    it("session exports expected functions", function()
      local mod = require("codediff.ui.lifecycle.session")
      assert.is_function(mod.get_active_diffs)
      assert.is_function(mod.create_session)
      assert.is_function(mod.compute_virtual_uri)
    end)

    it("accessors exports getter functions", function()
      local mod = require("codediff.ui.lifecycle.accessors")
      assert.is_function(mod.get_session)
      assert.is_function(mod.get_mode)
      assert.is_function(mod.get_git_context)
      assert.is_function(mod.get_buffers)
      assert.is_function(mod.get_windows)
      assert.is_function(mod.get_paths)
      assert.is_function(mod.find_tabpage_by_buffer)
      assert.is_function(mod.is_original_virtual)
      assert.is_function(mod.is_modified_virtual)
      assert.is_function(mod.is_suspended)
      assert.is_function(mod.get_explorer)
    end)

    it("accessors exports setter functions", function()
      local mod = require("codediff.ui.lifecycle.accessors")
      assert.is_function(mod.update_suspended)
      assert.is_function(mod.update_diff_result)
      assert.is_function(mod.update_changedtick)
      assert.is_function(mod.update_mtime)
      assert.is_function(mod.update_paths)
      assert.is_function(mod.update_buffers)
      assert.is_function(mod.update_git_root)
      assert.is_function(mod.update_revisions)
      assert.is_function(mod.set_explorer)
    end)

    it("conflict_state exports getter and setter functions", function()
      local mod = require("codediff.ui.lifecycle.conflict_state")
      assert.is_function(mod.get_merge_base_lines)
      assert.is_function(mod.get_result_base_lines)
      assert.is_function(mod.get_result)
      assert.is_function(mod.get_conflict_blocks)
      assert.is_function(mod.get_conflict_files)
      assert.is_function(mod.get_unsaved_conflict_files)
      assert.is_function(mod.set_result)
      assert.is_function(mod.set_result_base_lines)
      assert.is_function(mod.set_merge_base_lines)
      assert.is_function(mod.set_conflict_blocks)
      assert.is_function(mod.track_conflict_file)
      assert.is_function(mod.confirm_close_with_unsaved)
    end)

    it("tab_keymaps exports keymap functions", function()
      local mod = require("codediff.ui.lifecycle.tab_keymaps")
      assert.is_function(mod.set_tab_keymap)
      assert.is_function(mod.clear_tab_keymaps)
    end)

    it("auto_sync exports the file-switch sync function", function()
      local mod = require("codediff.ui.lifecycle.auto_sync")
      assert.is_function(mod.setup_auto_sync_on_file_switch)
    end)

    it("state exports expected functions", function()
      local mod = require("codediff.ui.lifecycle.state")
      assert.is_function(mod.save_buffer_state)
      assert.is_function(mod.restore_buffer_state)
      assert.is_function(mod.clear_buffer_highlights)
      assert.is_function(mod.get_file_mtime)
      assert.is_function(mod.suspend_diff)
      assert.is_function(mod.resume_diff)
    end)

    it("cleanup exports expected functions", function()
      local mod = require("codediff.ui.lifecycle.cleanup")
      assert.is_function(mod.setup_autocmds)
      assert.is_function(mod.cleanup)
      assert.is_function(mod.cleanup_all)
      assert.is_function(mod.setup)
    end)

    it("init facade delegates all functions", function()
      local mod = require("codediff.ui.lifecycle")
      assert.is_function(mod.create_session)
      assert.is_function(mod.cleanup)
      assert.is_function(mod.cleanup_all)
      assert.is_function(mod.setup)
      assert.is_function(mod.get_session)
      assert.is_function(mod.get_mode)
      assert.is_function(mod.get_buffers)
      assert.is_function(mod.get_windows)
      assert.is_function(mod.set_explorer)
    end)

    it("init facade delegates effects functions", function()
      local mod = require("codediff.ui.lifecycle")
      assert.is_function(mod.set_keymap)
      assert.is_function(mod.set_win_opt)
      assert.is_function(mod.restore_buffer)
      assert.is_function(mod.restore_window)
      assert.is_function(mod.restore_keymaps)
      assert.is_function(mod.restore_window_opts)
      assert.is_function(mod.restore_all)
      assert.is_function(mod.detach_buffer)
    end)

    it("effects module exports expected functions", function()
      local ok, mod = pcall(require, "codediff.ui.lifecycle.effects")
      assert.is_true(ok, "Failed to require codediff.ui.lifecycle.effects")
      assert.is_function(mod.set_keymap)
      assert.is_function(mod.set_win_opt)
      assert.is_function(mod.restore_buffer)
      assert.is_function(mod.restore_window)
      assert.is_function(mod.restore_keymaps)
      assert.is_function(mod.restore_window_opts)
      assert.is_function(mod.restore_all)
      assert.is_function(mod.detach_buffer)
    end)
  end)

  describe("circular dependency safety", function()
    it("accessors can call get_active_diffs at runtime", function()
      local accessors = require("codediff.ui.lifecycle.accessors")
      -- Should not error - returns nil for non-existent tabpage
      local result = accessors.get_session(99999)
      assert.is_nil(result)
    end)

    it("state suspend_diff handles missing session gracefully", function()
      local state = require("codediff.ui.lifecycle.state")
      -- Should not error on non-existent tabpage
      local ok = pcall(state.suspend_diff, 99999)
      assert.is_true(ok, "suspend_diff should not error on missing session")
    end)
  end)
end)
